export const REQUEST_THEMES = 'REQUEST_THEMES'
export const RECEIVE_THEMES = 'RECEIVE_THEMES'

export const REQUEST_NEWS = 'REQUEST_NEWS'
export const RECEIVE_NEWS = 'RECEIVE_NEWS'

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_LONG_COMMENTS = 'RECEIVE_LONG_COMMENTS'
export const RECEIVE_SHORT_COMMENTS = 'RECEIVE_SHORT_COMMENTS'